name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: create temporary tokens resource file
      run: echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><resources><string name=\"consumer_key\">CK</string><string name=\"consumer_secret\">CS</string></resources>" > /home/runner/work/Rumble/Rumble/app/src/main/res/values/tokens.xml
    - name: Build with Gradle
      run: sudo ./gradlew build
